MODULE MyCompany;

REQUIRE Eval, ProcessMonitor, Backup, Chat,
        MasterDataP,
        Inventory,
        Invoicing, InvoicingInventory,
        Purchase,
        Sales,
        Retail,  
        Manufacturing,
        ProjectManagement,
        HumanResources,
        CRM,
        Fleet,
        SumAddPOS, ReceiptPrinterAddPOS,
        BillReceiptCost, BillReceiptCostService; // initialize after Purchase