name: Sync Master with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Обнови до v4, она стабильнее
        with:
          ref: main # Замени на нужную ветку (main или master)
          fetch-depth: 0 # Полная история для ребейза

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Sync with upstream
        run: |
          set -e # Останавливай при ошибке
          git remote add upstream https://github.com/lsfusion-solutions/mycompany.git
          git fetch upstream
          git checkout main # Замени на нужную ветку
          if git rebase upstream/main; then
            echo "Rebase OK, pushing..."
            git push origin main --force-with-lease
          else
            echo "Rebase failed, trying merge..."
            git rebase --abort
            git merge upstream/main --no-edit
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}